dist: trusty
services:
  - mysql
  - mongodb
before_script:
  - npm install -g @angular/cli
  - npm install
  - sleep 15
  - mongo studybuddies --eval 'db.createUser({user:"travis",pwd:"test",role:["readWrite"]});'
before_install:
  - mysql -e 'CREATE DATABASE studybuddies;'
language: node_js
node_js:
  - "14.16.0"
install:
  - npm install codacy-coverage
script:
  - npm update
  - npm run build
