dist: trusty
services:
  - mysql
  - mongodb
before_script:
  - sleep 15
  - mongo studybuddies --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - npm install -g @angular/cli
  - npm install
before_install:
  - mysql -e 'CREATE DATABASE studybuddies;'
language: node_js
node_js:
  - "12.21.0"
install:
  - npm install codacy-coverage
script:
  - npm update
  - npm run build  
