language: node_js
node_js:
  - "14.16.0"
services:
  - mysql
  - mongodb
before_script:
  - sleep 15
  - mongo studybuddies --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - npm install -g @angular/cli
  - npm install
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download
before_install:
  - mysql -e 'CREATE DATABASE studybuddies;'
install:
  - npm install codacy-coverage --save
script:
  - npm update
  #- npm run start
  #- npm test -- --no-watch --no-progress --code-coverage
  - cd test
  - npm run test
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r test/coverage/lcov.info
