dist: trusty
services:
  - mysql
  - mongodb
before_script:
  - sleep 15
  - mongo studybuddies --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - npm install -g @angular/cli
  - npm install
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download
before_install:
  - mysql -e 'CREATE DATABASE studybuddies;'
language: node_js
node_js:
  - "12.21.0"
install:
  - npm install codacy-coverage --save
script:
  - npm update
  # npm run start
  #- npm test -- --no-watch --no-progress --code-coverage
  - cd test
  - istanbul cover -- login.test.js geRooms.test.js createRooms.test.js 
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r test/coverage/lcov.info
